/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesAutomatedKobotoolboxMonitoringRouteImport } from './routes/guides.automated-kobotoolbox-monitoring'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesAutomatedKobotoolboxMonitoringRoute =
  GuidesAutomatedKobotoolboxMonitoringRouteImport.update({
    id: '/guides/automated-kobotoolbox-monitoring',
    path: '/guides/automated-kobotoolbox-monitoring',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guides/automated-kobotoolbox-monitoring': typeof GuidesAutomatedKobotoolboxMonitoringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guides/automated-kobotoolbox-monitoring': typeof GuidesAutomatedKobotoolboxMonitoringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guides/automated-kobotoolbox-monitoring': typeof GuidesAutomatedKobotoolboxMonitoringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guides/automated-kobotoolbox-monitoring'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guides/automated-kobotoolbox-monitoring'
  id: '__root__' | '/' | '/guides/automated-kobotoolbox-monitoring'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuidesAutomatedKobotoolboxMonitoringRoute: typeof GuidesAutomatedKobotoolboxMonitoringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/automated-kobotoolbox-monitoring': {
      id: '/guides/automated-kobotoolbox-monitoring'
      path: '/guides/automated-kobotoolbox-monitoring'
      fullPath: '/guides/automated-kobotoolbox-monitoring'
      preLoaderRoute: typeof GuidesAutomatedKobotoolboxMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuidesAutomatedKobotoolboxMonitoringRoute:
    GuidesAutomatedKobotoolboxMonitoringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
